export { V2Badge } from "./V2Badge"
export { V2Badge as V2StatusBadge } from "./V2Badge" // Alias
export { V2Button } from "./V2Button"
export { V2DataTable, V2Table, type V2DataTableColumn, type V2DataTableColumn as V2TableColumn } from "./V2DataTable"
export { V2Dropdown } from "./V2Dropdown"
export { V2EmptyState, type V2EmptyStateProps } from "./V2EmptyState"
export { V2ErrorState, type V2ErrorStateProps } from "./V2ErrorState"
export { V2FilterBar, V2Toolbar, type V2FilterBarProps } from "./V2FilterBar"
export { V2IconButton } from "./V2IconButton"
export { V2Input } from "./V2Input"
export { V2KpiCard, type V2KpiCardProps } from "./V2KpiCard"
export { V2LoadingState, type V2LoadingStateProps } from "./V2LoadingState"
export { V2Modal, type V2ModalProps, type V2ModalSize } from "./V2Modal"
export { V2Drawer, type V2DrawerProps, type V2DrawerSide, type V2DrawerSize } from "./V2Drawer"
export { V2ConfirmDialog, type V2ConfirmDialogProps, type V2ConfirmTone } from "./V2ConfirmDialog"
export { V2Popover, type V2PopoverProps, type V2PopoverPlacement, type V2PopoverAlign } from "./V2Popover"
export { V2Tooltip, type V2TooltipProps, type V2TooltipPlacement } from "./V2Tooltip"
export { V2Toast, V2ToastViewport, type V2ToastProps, type V2ToastTone, type V2ToastAction } from "./V2Toast"
export { V2PageHeader } from "./V2PageHeader"
export { V2Pagination, type V2PaginationProps } from "./V2Pagination"
export { V2SectionCard } from "./V2SectionCard"
export { V2Select } from "./V2Select"
export { V2StatusSelect, type V2StatusSelectOption, type V2StatusSelectTone } from "./V2StatusSelect"
export { V2Skeleton } from "./V2Skeleton"
export { V2StatusDot } from "./V2StatusDot"
export { V2Tabs } from "./V2Tabs"

// Componentes Nuevos SIG Design Language V2
export { V2ExecutiveHeader } from "./V2ExecutiveHeader"
export { V2TrendIndicator } from "./V2TrendIndicator"
export { V2AlertCard } from "./V2AlertCard"
export { V2MetricCard } from "./V2MetricCard"
export { V2ChartCard } from "./V2ChartCard"
export { V2StatusBreakdown } from "./V2StatusBreakdown"
export { V2ActivityTimeline } from "./V2ActivityTimeline"
export { V2IntelligencePanel } from "./V2IntelligencePanel"
export { V2FinancialSummary } from "./V2FinancialSummary"
export { V2SectionHeader } from "./V2SectionHeader"
export { V2QuickActions } from "./V2QuickActions"
export { V2FormField } from "./V2FormField"
